monitoring:
  url: ${ENV_URL}
  port: 8080
  timeout: 2000

  scheduler:
    availability: ${SCHEDULER_AVAILABILITY}

  email:
    smtp:
      host: ${SMTP_HOST}
      port: ${SMTP_PORT}
      username: ${SMTP_USERNAME}
      appPassword: ${SMTP_PASSWORD}
    ssl:
      port: 465
    message:
      subject: "Availability result"
      template: "Host: %s\nAvailability: %s\nDate: %s\nPort: %s"
      destination: ${MESSAGE_DESTINATION}

server:
  servlet:
    context-path: "/api"

logging:
  file:
    path: ./src/main/resources/log
